run:
    just run-basic

run-basic:
    python service.py


run-beanie:
    python service-beanie.py


update-reqs:
    pip-compile requirements.in
    pip-compile dev-requirements.in

deps:
    python -m pip install -r requirements.txt -r dev-requirements.txt